### ISSUE TITLE
Using pandoc to turn URLs of hyperlinks into footnotes

### ISSUE THREAD

**Issue by fkohrt** [yihui/rmarkdown-cookbook#204]
I just discovered that besides the [code](https://github.com/yihui/rmarkdown-cookbook/blob/e6e47d7/05-latex.Rmd#L24-L26) that illustrates a possible use of adding LaTeX code to the preamble, there's an even easier way to turn URLs of hyperlinks into footnotes: Pandoc's [`links-as-notes`](https://pandoc.org/MANUAL.html#links) metadata field!

It may be a good idea to add that to the guide :)

**Comment by cderv** [comment]
Thank you ! 

For reference, this is related to other issue about PANDOC know-how  #169 and #106

**Comment by yihui** [comment]
Thanks! I didn't use `links-as-notes` because sometimes I still need the old `\href` command, e.g.,

https://github.com/rstudio/bookdown/blob/cd97d40eccd2ce8d05e39b7815ede59f7b3aa4d6/inst/examples/02-components.Rmd#L787-L794

Pandoc's implementation is a little different and I won't have access to the original `\href`:

https://github.com/jgm/pandoc/blob/9c2b659eeb196145f62d8eae0072c279a7c2d751/data/templates/default.latex#L290-L293

Anyway, I'll mention this YAML option in the book. Thanks again!

**Comment by fkohrt** [comment]
Yeah, very true. There's a nice [LaTeX solution](https://tex.stackexchange.com/a/28863) to showing URL break indicators that conflicts with `links-as-notes` for the same reason.
