### ISSUE TITLE
Add index entries

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#207]
Add `\index{}` wherever appropriate.

**Comment by emilyriederer** [comment]
Hi @yihui - do you have a "favorite" index from a past book project where you particularly like the level of detail? I'd love to look at an example to better understand the desired level of detail for what merits an index entry. Thank you!

**Comment by cderv** [comment]
I can also help on that at some point - you tell me if you have time or not. However, it may be better to have one person deal with the all chapters. Feel free to ping me if necessary

**Comment by yihui** [comment]
I don't have a favorite one, but here are the index pages for

## R Markdown: the Definitive Guide

![image](https://user-images.githubusercontent.com/163582/85930299-cfcf1080-b880-11ea-83b5-62ff20692d43.png)

## the blogdown book

![image](https://user-images.githubusercontent.com/163582/85930327-0442cc80-b881-11ea-8fa5-0b81efd5148f.png)

## the bookdown book

![image](https://user-images.githubusercontent.com/163582/85930337-1a508d00-b881-11ea-8e0e-ba947a5e701a.png)

Personally I don't care much about the index, but some readers really love it. Some have even complained that my indexes were too short.

BTW, this job needs to be done after the content is finalized, and we haven't reached that stage yet (hopefully soon will), so please hold on.

**Comment by emilyriederer** [comment]
Thanks, @yihui ! These are very helpful. We will definitely hold off actually *adding* any entries for now, but it may be helpful to start thinking what these entries should be.

@cderv ! I really appreciate that. As a start, perhaps we should both start brainstorming index entries. It seems like the process will be much more efficient if there's a reasonably comprehensive list before indexing begins (for less backtracking). To be honest, one place that I am particularly insecure is the LaTeX chapter because I haven't used LaTeX enough to have an intuition for what users would tend to look for.

**Comment by yihui** [comment]
> it may be helpful to start thinking what these entries should be.

Definitely!

**Comment by cderv** [comment]
I suggest to list the index entries we want in this google sheets
https://docs.google.com/spreadsheets/d/1Lcd81ds5i9Ybj6KZzo_f0xLTp_DROKiiNm6FUcMOJ7Y/edit?usp=sharing

One column, One letter, to regroup entries alphabetically.

**Comment by emilyriederer** [comment]
Thank you, @cderv ! That's a great idea. I really like the layout

**Comment by emilyriederer** [comment]
I'm not sure if we want package names in the Appendix, but if so, I will probably scrape all package names next Friday for #208, so I can add them to the Google sheets then

**Comment by emilyriederer** [comment]
@yihui - One more question on the timeline. Should this and #208 be done before or after its sent for copy-editing? I'm assuming #210 must be done afterwards and as the very last thing, but I wasn't clear on the other two. Thanks!

**Comment by yihui** [comment]
@emilyriederer This issue can be done at any time after the content is finalized (it doesn't matter if it is before or after copy-editing). #208 needs to be done before copy-editing. #210 after copy-editing.

**Comment by emilyriederer** [comment]
On second thought regarding my comment about package names, after doing the references, I note that most of the packages only come up a single time. I am thinking it does **not** make sense to index them, then, as specific package names probably are not what readers would tend to be looking for versus general concepts. Please let me know if you agree!

**Comment by yihui** [comment]
If a package is widely known, it probably makes sense to put it in the index, otherwise the index entry won't be very useful. I'll just let you weigh on the popularity of these packages.

**Comment by emilyriederer** [comment]
Hi All! I'm starting to experiment with the index and keep changing my mind exactly how I want to do it. I know @yihui mentioned that some readers have wished for more detailed indexes before. Do either of you have any opinions on subindexes? I notice the examples don't use this feature so I wasn't sure if there were specific disadvantages that I should consider. For example, I was thinking:

- if I index packages, can subindex noteworthy functions
- for some things like YAML options or chunk options it might be a good way to organize 

Here's a very minimal example as I test out different things with the first four chapters:

![image](https://user-images.githubusercontent.com/19798371/87785808-706c7c80-c7fe-11ea-8dee-58149f62de5f.png)

Also, one question: when I am using the `see also` command, is there a single file you where it would make sense to put all of these (e.g. the end of the very last chapter?) Since these only need to get used one time each instead of at every occurence, it seemed like it might be nice to consolidate them instead of having them sprinkled throughout the text.

**Comment by cderv** [comment]
I really like the subindex feature. I did not think of that but now I find it helpful to discover related topics. 👍
