### ISSUE TITLE
Mention R Markdown templates

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#230]
One reviewer suggested after https://bookdown.org/yihui/rmarkdown-cookbook/package-vignette.html:

> If mentioning package collateral at all (as-in section 16.6), RMarkdown templates should also be highlighted as a less common but highly valuable thing to add to a package. Similar to 16.6, there could be a brief explanation of the infrastructure required as well as shortcuts such as `usethis::use_rmarkdown_template`.

**Comment by cderv** [comment]
I understand the reviewer, and I think it could be mentioned. We did not develop a part on this in the book because it was already included in the Definitive Guide with details : https://bookdown.org/yihui/rmarkdown/document-templates.html

However, `usethis::use_rmarkdown_template` is a create recipe to know. Thanks for the PR @emilyriederer

**Comment by emilyriederer** [comment]
Thanks for the pointing out the duplication with the Definitive Guide, @cderv ! That's a good point. There are so many good resources it is hard to keep track of them all. This definitely provides a more thorough explanation than my PR. We can continue the discussion over there, but I'm definitely happy to make that even shorter (or reject it altogether) to avoid the redundancy.
