### ISSUE TITLE
How to share HTML output documents on the web

### ISSUE THREAD

**Issue by yihui** [yihui/rmarkdown-cookbook#232]
One reviewer suggested:

> Perhaps authors would like to include some recommendations of how to share html outputs on the web? E.g. RPubs, netlify, github pages.

Sounds like a good suggestion to me. I'll let you decide.

**Comment by emilyriederer** [comment]
Does anyone have any thoughts on this one how much detail to include? I worry that it might not be useful to name the services without more description of how to use them. However, website interfaces and favored platforms change so fast these days (e.g. GitHub Actions lately seems to be gaining a lot of popularity of Travis CI) that I am trying to think how to write this in a way that is helpful but safeguards the content from quickly going stale.

**Comment by cderv** [comment]
I think we can try to categorize the different possibility users have. Personally I would present this topic in this way

* First, remind that HTML rmarkdown output are static websites, unless using shiny runtime. They can be self contained for most of them (but not all) and thus shared easily as-is in one file. But sometimes, it is easier to not produce self contained document, and host them somewhere. 
* Maybe we could remind a static website is an `index.html` with other html document, some css, js and other files (like images). 

That being said, how one can publish its production ? 

* Hosted services:
    * R specific service for Rmarkdown output: Some R function allows to publish into those services using `rsconnect` package
        * Rpubs : , integrated with RStudio IDE and dedicated to html Rmakdown output *without shiny runtime*
        * shinyapps.io : for shiny runtime document. 
        * bookdown.org: Specific for sharing bookdown content (https://bookdown.org/home/about/)
        * RStudio Connect: Professional product, on premise for company. Integrated with RStudio IDE, support everything Rmarkdown can produce.
   * Static website service: 
       * Netlify: Hosting service for static website stack. Will support any non shiny runtime production. Mostly use for Blogdown or pkgdown website, but can be used to publish one document also. Great resource: https://rstudio.com/resources/webinars/sharing-on-short-notice-how-to-get-your-materials-online-with-r-markdown/ . One can publish by drag and drop or using a cli tool : most often this is integrated into continuous deployment pipeline
      * CI related hosting service (Github Pages, Gitlab Pages) : Allows to easily serve a static website from files that are included in the code repository service (Github, Gitlab). Either published by continuous deployment pipeline or by putting the website file into a specific folder in the repository or being the repository itself. (For Github page)
     * Self hosting method using any web server : using apache, nginx or else, one can decide to host itself its documents or website. On its own servers or using docker container. 

I would only mentions all the possibility without getting to much into details, and example as one can easily find some in the community when they know what to search. We could also add some link to blogpost or example of how to do the publication.
Trying to add detailed example may require to give some for each format. There is already a chapter like that for blogdown: https://bookdown.org/yihui/blogdown/deployment.html
We could work on whole chapter about deployment in a second edition, by taking the time to create examples and recipes for each format, with each services. Some work but would be useful I guess. 

> However, website interfaces and favored platforms change so fast these days (e.g. GitHub Actions lately seems to be gaining a lot of popularity of Travis CI) 
I see the CI tools as a mean to automate a publishing on the hosting service or environment. For me, the main point here is to mention the "Where to host what" more than the "how to create the pipeline to automate a publication". Does it make sense ? 

BTW, example of why a chapter on this topic can be useful: https://github.com/rstudio/flexdashboard/issues/266#issuecomment-636328900

@emilyriederer I hope it helps you decide what could be done. Please tell me how I can help on this.

**Comment by emilyriederer** [comment]
Thank you so much, @cderv ! This is a fantastic breakdown. It definitely helped make sense to me that we can give readers a framework for understanding the different types of services instead of getting too tactical with specific details on how to use any individual option. 

Would you like to write this part or should I? You've already done the hard part coming up with a good way to arrange all the content. I don't want to "plagiarize" by taking your good outline and ideas and just turning it into paragraphs, but I'm happy to do so if you would rather not. Please just let me know! 😄

**Comment by cderv** [comment]
Glad it make sense! It was a rough outline, but I am happy you get the idea. I think this would be very useful to help users understand how this works and give them the _keywords_ to look for what they need. I find Googling way more efficient when you understand what you are looking for. ("How to deploy a blogdown website to Netlify from Github ?" rather than "how to publish a Rmarkdown content ?" )

> Would you like to write this part or should I? 

I don't mind you writing it. you are more used to write than me, all the more that as a non native english speaker or writer, my writing would require you to pass behind me for sure. 


>  You've already done the hard part coming up with a good way to arrange all the content. I don't want to "plagiarize" by taking your good outline and ideas and just turning it into paragraphs, but I'm happy to do so if you would rather not

we are co-authors now, so you can take my ideas without hesitation, I put them there for you 😄  
And as you are happy to do so, be my guest. I'll keep my role of giving ideas, and reviewing the content on this one 😉
