### ISSUE TITLE
Why not just use the LaTeX package 'awesomebox' for the warning box, infobox etc

### ISSUE THREAD

**Issue by krishnakumarg1984** [yihui/rmarkdown-cookbook#249]
The LaTeX package [`awesomebox`](https://ctan.org/pkg/awesomebox) is tailor-made for the purpose of typesetting the warning and info boxes and a whole lot more.

Its documentation says:

> Awesome Boxes is all about drawing admonition blocks around text to inform or alert readers about something particular. The specific aim of this package is to use FontAwesome icons to ease the illustration of these blocks. 

Can you please suggest a way to use these instead?

**Comment by yihui** [comment]
> Why not just use the LaTeX package 'awesomebox'

Because I have never heard of it until you told me here.

> Can you please suggest a way to use these instead?

Yes, you can remix two recipes in this book:

- how to load a LaTeX package: https://bookdown.org/yihui/rmarkdown-cookbook/latex-extra.html
- how to generate a LaTeX environment with a fenced Div: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html

**Comment by yihui** [comment]
It's mentioned at the end of this section now: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html

**Comment by krishnakumarg1984** [comment]
@yihui Thank you. I really didn't do all that much. The acknowledgement came unexpectedtly and was a nice gesture from you!
