### ISSUE TITLE
How to contribute to the cookbook

### ISSUE THREAD

**Issue by apreshill** [yihui/rmarkdown-cookbook#291]
I just forked the book and tried to build it locally and see all kinds of errors, eventually stopping with this one:
```
Quitting from lines 4272-4277 (rmarkdown-cookbook.Rmd) 
Error in getMetricsFromLatex(TeXMetrics, verbose = verbose) : 
TeX was unable to calculate metrics for:

	m

Run the following commands for diagnosis:

	tikzTest()
	tikzTest("m")

Common reasons for failure include:
  * The string contains a character which is special to LaTeX unless
    escaped properly, such as % or $.
  * The string makes use of LaTeX commands provided by a package and
    the tikzDevice was not told to load the package.

The TeX and log files used for the calculation can help diagnose the
problem. If these files are missing, rerun the plot and make sure to
keep the R session open.
TeX file: tikzStringWidthCalc.tex
Log file: tikzStringWidthCalc.log
```

I probably cannot fix it, but wanted to offer that with the [stat545](https://stat545.com/) bookdown repo, we obsessed over making instructions so folks could build the book locally and contribute to it. Perhaps what we did might be useful here? 

https://github.com/rstudio-education/stat545#requirements-to-preview-the-site-locally

**Comment by cderv** [comment]
Oh yes we did not do that here ! It was even painful for @emilyriederer and I to build the book on our side when working on it ! 😅 

Tidymodel book has also an explanation about how to run the book. 

@emilyriederer what do you think ? 

We may need to remove that / opt-out some part of the book that requires specific system requirement not easy to meet (thinking of asymptote here)

Thank for opening this issue @apreshill !

**Comment by emilyriederer** [comment]
Haha - yes! Building the book is definitely not very obvious 😄 

Thanks, @apreshill . I really like this idea. 

I'm trying to remember the things that were the trip ups for me. In addition to R packages, like in the example, we would need to include information about installing fonts, LaTeX packages, external software like Asymptote. Alternatively, @cderv, I really like the idea of making it possible to opt-out chunks or perhaps even chapters. For chunks, we could even just add a chunk option `eval = param$opt_out` for potentially problematic sections. 

Alternatively or additionally, if the main use case is enabling contribution, we could also look into building PRs with GitHub Actions. I haven't set this up myself before, but I believe it is possible based on blog posts [like this](https://medium.com/@delucmat/how-to-publish-bookdown-projects-with-github-actions-on-github-pages-6e6aecc7331e).

Which do you think is the better option?

Before we take action here, I wonder if we need to check with the publisher? I know we weren't supposed to distribute the PDF widely during the editing phase, so I'm not sure if that's at all a contractual issue?

**Comment by cderv** [comment]
I think we should make the html book easy to build for other to contribute. For the PDF, I am note sure either what is ok. 

Regarding opt out we could also make some sections conditional to some système requirement like asymptote instead of blocking the build. 

@apreshill is the issue with the HTML version ? Or the PDF version ? 

@emilyriederer I can add a GHA build for PR. with preview that would be the best IMO !

**Comment by emilyriederer** [comment]
Oh - good point. I wasn't even thinking about the HTML. I'm not sure why my mind went straight to the PDF (probably because that was the more acute issue for us!) I definitely do like the idea of removing the friction there. I have a couple of hectic work weeks ahead so I won't get to it immediately, but in December, I'm happy to take a first pass at setting something up like the STAT545 example

**Comment by apreshill** [comment]
I think HTML would be a great place to start! Leaving this link here in case it is useful:

https://www.hvitfeldt.me/blog/bookdown-netlify-github-actions/

Stat545 is still built on Travis:
https://github.com/rstudio-education/stat545/blob/master/.travis.yml

This is probably the most up to date GH action I know of for building a bookdown HTML book- I believe they have wired it up so that external PRs trigger a deploy preview in Netlify, which is a nice element!
https://github.com/hadley/r-pkgs/blob/master/.github/workflows/build-book.yaml

**Comment by cderv** [comment]
@apreshill about the specific issue you have, I encountered it also on working on knitr. It is some latex packages missing to make the tikz device work. They should have been installed automatically. 

Can you share the result of 
```r
pkgs <- c('pgf', 'preview', 'xcolor', 'grfext')
setNames(pkgs %in% tinytex::tl_pkgs(), pkgs)
```

I wonder if the `grfext` package is now required. 🤔 

Thank you

**Comment by apreshill** [comment]
I see:
```
> pkgs <- c('pgf', 'preview', 'xcolor', 'grfext')
> setNames(pkgs %in% tinytex::tl_pkgs(), pkgs)
    pgf preview  xcolor  grfext 
   TRUE   FALSE    TRUE    TRUE
```

When I try to preview the book:

```
label: dev-tikz (with options) 
List of 7
 $ dev        : chr "tikz"
 $ tidy       : logi FALSE
 $ fig.cap    : chr "A plot rendered via the tikz device."
 $ fig.dim    : language c(6, 4)
 $ fig.align  : chr "center"
 $ fig.process: symbol pdf2png
 $ cache      : logi TRUE

Quitting from lines 4272-4277 (rmarkdown-cookbook.Rmd) 
Error in getMetricsFromLatex(TeXMetrics, verbose = verbose) : 
TeX was unable to calculate metrics for:

	m

Run the following commands for diagnosis:

	tikzTest()
	tikzTest("m")

Common reasons for failure include:
  * The string contains a character which is special to LaTeX unless
    escaped properly, such as % or $.
  * The string makes use of LaTeX commands provided by a package and
    the tikzDevice was not told to load the package.

The TeX and log files used for the calculation can help diagnose the
problem. If these files are missing, rerun the plot and make sure to
keep the R session open.
TeX file: tikzStringWidthCalc.tex
Log file: tikzStringWidthCalc.log
```

**Comment by cderv** [comment]
> ```
> pkgs <- c('pgf', 'preview', 'xcolor', 'grfext')
> setNames(pkgs %in% tinytex::tl_pkgs(), pkgs)
    pgf preview  xcolor  grfext 
   TRUE   FALSE    TRUE    TRUE

You are missing the preview package - It should have installed by its own (but I'll look into that). 

You can do 
```r
tinytex::tlmgr_install("preview")
```

And it should work after that (at least this bug should disappear)

These packages are required for tikz device (we have this device explained in the book)

**Comment by apreshill** [comment]
I haven't had a need to use tikz devices so have no clue :) I ran that install though:

```
label: elevation (with options) 
List of 5
 $ fig.cap   : chr "A 3D graph made with Asymptote."
 $ cache     : logi TRUE
 $ fig.retina: num 1
 $ eval      : language is.na(Sys.getenv("CI", NA))
 $ engine    : chr "asy"

running: 'asy' 'code98e44d32ddb' -f png -o 'out98e467a82a.png'
sh: asy: command not found
Quitting from lines 5758-5776 (rmarkdown-cookbook.Rmd) 
Error in engine(options) : Failed to compile the asy chunk
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In file.rename(f2, outf) :
  cannot rename file 'out98e467a82a.png' to 'rmarkdown-cookbook_files/figure-html/elevation-1.png', reason 'No such file or directory'
```

**Comment by cderv** [comment]
Ok this is the issue we where expected with @emilyriederer! The one which require `asymptote ` dependency. not an easy one. 

So the first issue is fixed then. 

We will stop here in the step-by-step resolution. I'll make some adjustments in the book so that we don't have issue with html output. And work on a github build for this book. I am currently deep in GHA for knitr and all so  I do that after. 

Sorry for the trouble @apreshill !

**Comment by emilyriederer** [comment]
Hey @cderv ! I find I'm actually have more time this week than I thought. Are there any of the adjustments and/or GHA you'd like me to help out with? Otherwise, still happy to do more documenting at the end, but it probably makes sense for us to make any structural changes first?

**Comment by cderv** [comment]
If you want to play with Github Action, you can open a PR to build the book. I still need to take care of other repos before. 

Otherwise, we could focus on documenting how to build the HTLM version of the book. That would be interesting for future us and for future collaborators. It should not be that difficult. All the R installable requirements are in the `index.Rmd`. 

* The issue described here is a missing latex package (`preview`). We may need to add it to be install by tinytex
* If there is system requirement, It think we should 
   * not eval the chunk to avoid error
   * and / or print a message that the requirement is missing. 

I think by making a wrapper function to pass to eval would do the trick. It should not error and I think it should not silently pass. (to have a "Do not forget" message, even for us.)

Also, this would allow us to have a clean base, which would be working, before doing any structural change for next version. 

What do you think ? Could you work on a PR that would add a 'how to build html version' locally ? 

You can try the GHA workflow if you prefer.

**Comment by emilyriederer** [comment]
I thought I typed a reply to this a few days back, but I was just referencing your comments and I see that it's not here -- sorry about that! Working on a PR for building the HTML now.
