### ISSUE TITLE
How to use R variable as reference_docx in Rmarkdown?

### ISSUE THREAD

**Issue by beibeiJ** [yihui/rmarkdown-cookbook#324]
Hi,

I have tried to use the following to use the dynamic template file path 
```
---
output:
  word_document:
    reference_docx: "`r params$template_path`"
---
```
but failed with 
```
Error: could not find file '`r params$template_path`'
```
I have printed `params$template_path` and the file was there. Any idea why it throws me this error? 

Thanks.

**Comment by cderv** [comment]
Hi @beibeiJ, 

First just as a general reminder, this is not really the place to ask generic question about R Markdown, you got Q&A site for that like https://community.rstudio.com

However, this is interesting because it is an edge case of how to use variable in YAML header. 

This field of the YAML header under `output` is used by R Markdown only during processing and not by Pandoc. This means you need to make the value available for processing before Pandoc is ran. This is different from a field like `title:` because inline code chunk will be replace at knit time and title will be parsed at Pandoc conversion time. 

The way to parametrized output options is to use the `output_options` argument in `render()`. This is the practical solution to modify the value when you are calling `render()`, like you would do with `params` but you don't need `params`

Try 
````r
rmarkdown::render("test.Rmd", output_options = list(reference_docx = "my_ref.docx"))
```

See [?render](https://rmarkdown.rstudio.com/docs/reference/render.html) for this argument. 

I would use this solution as this is very close to using `rmarkdown::render(..., params = list(template_path = "my_ref.docx")`

Would that work for you ?

**Comment by beibeiJ** [comment]
@cderv many thanks for the reminder and the solutions. I tried the first solution and it works for me quite well.
