### ISSUE TITLE
Clarify structure of book

### ISSUE THREAD

**Issue by dr-harper** [yihui/rmarkdown-cookbook#4]
I am keen to set this project up to make it easy for others to contribute to. A big part of this is trying to clarify the exact purpose of the book, and a general structure of the book chapters and content.

My initial thoughts would be that the book would offer some examples of how to extend R Markdown, with useful tips and tricks for intermediate/advanced users. It would be aimed at people who had read the R Markdown Definitive Guide so skip a lot of the basics often covered in R Markdown guides (markdown syntax etc.).

You can see I have tried to establish a structure for the overall book of things I think are worth covering, but again these are fairly adaptable and open to amendments.

**Comment by yihui** [comment]
I guess my initial thought was relatively simple: go through all Stack Overflow questions about R Markdown, and summarize/refine the solutions. This is actually how I wrote some parts of the knitr book.

For this book, the first 500 questions (sorted by votes) may be enough: https://stackoverflow.com/questions/tagged/r-markdown?sort=votes&pagesize=50 If we are fast enough, we could take a look at more posts.

The advantage of this approach is that we have some evidence that we are writing a book that people actually need, instead of simply hoping people would love it.

A cookbook, by definition, contains recipes. I hope each recipe could be relatively short (one to three pages sounds about right to me). I tend to target at beginners and intermediate users. We could work on a third book "R Markdown Ninja" in perhaps 2020 dedicated to advanced users :)

I'm fine if the chapter/part titles change as we work on the book. We don't need to decide them at this point.

**Comment by cderv** [comment]
> For this book, the first 500 questions (sorted by votes) may be enough
I am willing to go through these and open issues to organize work here. I am still not sure if one issue per theme with checkbox, or one issue per idea is better... Will see. If you have experience, please share.

**Comment by cderv** [comment]
I began to open issues for the first SO questions in the top 500. My idea is to put almost every idea here to share what is interesting or not. You can then close the issues for questions that do not make good recipes for this book. 
Going through the questions on SO, we can also add into existing issues if related. We can also discuss answer as there are in the top old questions with old answers. This cookbook is a the good way to update all these.

Hope this is fine. I don't mind to keep on going through SO question but I will stop for a few days waiting for your thoughts on this process. I don't want to open to many issues if you prefer to work another way. 😉

**Comment by yihui** [comment]
That is fine to me. Thanks!

**Comment by yihui** [comment]
Preface: https://bookdown.org/yihui/rmarkdown-cookbook/
